project/apps/Home/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_request, name="login"),
    path("logout/", LogoutView.as_view(template_name="Home/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
]  

urlpatterns += staticfiles_urlpatterns()

project/apps/cliente/urls.py
from django.urls import path
from .views import home, crear_clientes, crear_cliente, busqueda #! Importación de la función home en views.py

app_name = "cliente"

urlpatterns = [
    path("", home, name="home"), #! HOME DE CLIENTE 
    path("crear_clientes", crear_clientes, name="crear_clientes"),
    path("crear/", crear_cliente, name="crear"), 
    path("busqueda", busqueda, name="busqueda"),
]

project/apps/producto/urls.py
from django.urls import path
from . import views #! Importación de la función en views.py

app_name = "producto"

# PRODUCTO CATEGORIA 
urlpatterns = [
    path("", views.index, name="home"), 
    path("productocategoria/list/", views.ProductoCategoriaList.as_view(), name="productocategoria_list"),
    path("productocategoria/create/", views.ProductoCategoriaCreate.as_view(), name="productocategoria_create"),
    path("productocategoria/detail/<int:pk>", views.ProductoCategoriaDetail.as_view(), name="productocategoria_detail"),
    path("productocategoria/update/<int:pk>", views.ProductoCategoriaUpdate.as_view(), name="productocategoria_update"),
    path("productocategoria/delete/<int:pk>", views.ProductoCategoriaDelete.as_view(), name="productocategoria_delete"),
]

# PRODUCTO
urlpatterns += [
    path("", views.index, name="home"), 
    path("producto/list/", views.ProductoList.as_view(), name="producto_list"),
    path("producto/create/", views.ProductoCreate.as_view(), name="producto_create"),
    path("producto/detail/<int:pk>", views.ProductoDetail.as_view(), name="producto_detail"),
    path("producto/update/<int:pk>", views.ProductoUpdate.as_view(), name="producto_update"),
    path("producto/delete/<int:pk>", views.ProductoDelete.as_view(), name="producto_delete"),
]

project/config/urls.py
#! URL PRINCIPAL
from django.contrib import admin
from django.urls import path, include #! INCLUDE SIRVE PARA TRAER URLS DE OTRAS APLICACIONES A ESTA URL QUE ES LA PRINCIPAL 
#from . import views #! Importación de las vistas de views.py (PARA LOS PATH)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Home.urls")),
    path("cliente/", include("cliente.urls")),
    path("producto/", include("producto.urls")),
]

project/apps/Home/models.py
from django.db import models

project/apps/Home/forms.py
from django import forms 
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {"username": forms.TextInput(attrs={"class": "form-control"}),
                   "password": forms.PasswordInput(attrs={"class": "form-control"})} 
        

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        widgets = {"username": forms.TextInput(attrs={"class": "form-control"}),
                   "password1": forms.PasswordInput(attrs={"class": "form-control"}),
                   "password2": forms.PasswordInput(attrs={"class": "form-control"})} 
        help_texts = {k: "" for k in fields}    

project/apps/Home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpResponse
from django.http.request import HttpRequest
from . import forms
from django.contrib.admin.views.decorators import staff_member_required


def home(request):
    return render(request, "Home/index.html")

#! LOGIN - LOGOUT

def login_request(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get("username")
            contraseña = form.cleaned_data.get("password")
            user = authenticate(username=usuario, password=contraseña)
            if user is not None:
                login(request, user)
                return render(request, "Home/index.html", {"mensaje": "Inició sesión correctamente"})
    else:
        form = forms.CustomAuthenticationForm()
    return render(request, "Home/login.html", {"form": form})


#! REGISTRO 

@staff_member_required
def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.CustomUserCreationForm(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data.get("username")
            form.save()
            return render(request, "Home/index.html", {"mensaje": "Alumno creado exitosamente."})
    else:
        form = forms.CustomUserCreationForm()
    return render(request, "Home/register.html", {"form": form})

project/apps/Home/templates/Home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Aplicación Web</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'Home/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'Home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>


        <!-- Responsive navbar-->
        {% include 'Home/navbar.html' %}

        <!-- Page Content-->
        {% block BASE_CONTENIDO %}
           
        {% endblock BASE_CONTENIDO %}

        <div class="container px-4 px-lg-5">
           
         

        <!-- Footer-->
        {% include 'Home/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'Home/js/scripts.js' %}"></script>
    </body>
</html>

project/apps/Home/templates/Home/card.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body text-center">
            <h2 class="card-title">{{ card }}</h2>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
        </div>
        <div class="card-footer"><a class="btn btn-success btn-sm" href="#!">Sobre las clases</a></div>
    </div>
</div>

project/apps/Home/templates/Home/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark fixex-bottom">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Sukata San Pedro 2024</p></div>
</footer>
     

project/apps/Home/templates/Home/index.html
{% extends 'Home/base.html' %}

{% block BASE_CONTENIDO %}

{% block INDEX_TITULO %}    
    Página de inicio
{% endblock INDEX_TITULO %}
<br>
    {% block INDEX_CONTENIDO %}
    <p class="fs-5 fw-bold text-body-emphasis">

        {% if user.is_authenticated %}
            {{ mensaje }}
            <h3>Bienvenido {{ user.username }}</h3>
        {% endif %}

        {% if user.is_staff %}
            <p><a href="{% url 'admin:index' %}">Panel de administracion</a></p>
            <p><a href="{% url 'Home:register' %}">Registrar nuevo usuario</p>
        {% endif %}
     </p>
    <!-- Heading Row-->
    
     <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://dummyimage.com/900x400/dee2e6/6c757d.jpg" alt="..." /></div>
        <div class="col-lg-5">
            <h1 class="font-weight-light">Sukata San Pedro</h1>
            <p>Academia de artes marciales mixtas</p>
            <a class="btn btn-primary" href="#!">Contactanos!</a>
        </div>
    </div>     
    
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        {% include 'Home/card.html' with card="Jiu Jitsu - Judo"%}
        {% include 'Home/card.html' with card="Grappling - MMA" %}
    </div>
    
    {% endblock INDEX_CONTENIDO %}

{% endblock BASE_CONTENIDO %}

project/apps/Home/templates/Home/login.html
{% extends 'Home/index.html' %}

{% block INDEX_TITULO %}
    Login
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Iniciar Sesión</button>
    </form>
{% endblock INDEX_CONTENIDO %}

project/apps/Home/templates/Home/logout.html
{% extends 'Home/index.html' %}

{% block INDEX_CONTENIDO %}
 <p class="fs-5 fst-italic">
     Sesión cerrada
 </p>
{% endblock INDEX_CONTENIDO %}

project/apps/Home/templates/Home/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Sukata San Pedro</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Home:home' %}">Inicio</a></li>

                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'cliente:home' %}">Alumnos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'producto:home' %}">Productos</a></li>
                <li class="nav-item"><a class="nav-link text-info" href="{% url 'Home:logout' %}">Logout</a></li>
                
                {% else %}
                <li class="nav-item"><a class="nav-link text-info" href="{% url 'Home:login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">Nosotros</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">Clases</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">Contacto</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

project/apps/Home/templates/Home/register.html
{% extends 'Home/index.html' %}

{% block INDEX_TITULO %}
    <div class="fst-italic">
        Registrarse: 
    </div>
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid gap-3">
            <button type="submit" class="btn btn-success">Registrarse</button>
        </div>
    </form>
{% endblock INDEX_CONTENIDO %}