project/apps/Home/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = "Home"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_request, name="login"),
    path("logout/", LogoutView.as_view(template_name="Home/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
]  

urlpatterns += staticfiles_urlpatterns()

project/apps/producto/urls.py
from django.urls import path
from . import views #! Importación de la función en views.py

app_name = "producto"

# PRODUCTO CATEGORIA 
urlpatterns = [
    path("", views.index, name="home"), 
    path("productocategoria/list/", views.ProductoCategoriaList.as_view(), name="productocategoria_list"),
    path("productocategoria/create/", views.ProductoCategoriaCreate.as_view(), name="productocategoria_create"),
    path("productocategoria/detail/<int:pk>", views.ProductoCategoriaDetail.as_view(), name="productocategoria_detail"),
    path("productocategoria/update/<int:pk>", views.ProductoCategoriaUpdate.as_view(), name="productocategoria_update"),
    path("productocategoria/delete/<int:pk>", views.ProductoCategoriaDelete.as_view(), name="productocategoria_delete"),
]

# PRODUCTO
urlpatterns += [
    path("", views.index, name="home"), 
    path("producto/list/", views.ProductoList.as_view(), name="producto_list"),
    path("producto/create/", views.ProductoCreate.as_view(), name="producto_create"),
    path("producto/detail/<int:pk>", views.ProductoDetail.as_view(), name="producto_detail"),
    path("producto/update/<int:pk>", views.ProductoUpdate.as_view(), name="producto_update"),
    path("producto/delete/<int:pk>", views.ProductoDelete.as_view(), name="producto_delete"),
]

project/config/urls.py
#! URL PRINCIPAL
from django.contrib import admin
from django.urls import path, include #! INCLUDE SIRVE PARA TRAER URLS DE OTRAS APLICACIONES A ESTA URL QUE ES LA PRINCIPAL 
#from . import views #! Importación de las vistas de views.py (PARA LOS PATH)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Home.urls")),
    path("cliente/", include("cliente.urls")),
    path("producto/", include("producto.urls")),
]

project/apps/producto/models.py
from django.db import models
from django.utils import timezone

class ProductoCategoria(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    descripcion = models.CharField(max_length=100, null=True, blank=True, verbose_name="Descripción")

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name = "Categoría de producto"
        verbose_name_plural = "Categorías de Productos"


class Producto(models.Model):
    """Productos que corresponden a una categoria"""
    categoria = models.ForeignKey(ProductoCategoria, on_delete=models.SET_NULL, blank=True, null=True)
    nombre = models.CharField(max_length=150)
    unidad_de_medida = models.CharField(max_length=150)
    cantidad = models.FloatField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.CharField(max_length=250, null=True, blank=True)
    fecha_actualizacion = models.DateTimeField(default=timezone.now, editable=False, verbose_name="Fecha de actualización")

project/apps/producto/forms.py
from django import forms
from . import models

class ProductoCategoriaForm(forms.ModelForm):
    
    class Meta:
        model = models.ProductoCategoria
        fields = "__all__"

class ProductoForm(forms.ModelForm):

    class Meta:
        model = models.Producto
        fields = "__all__"
        

project/apps/producto/views.py
from django.shortcuts import render, redirect
from . import models
from . import forms
from django.http import HttpResponse, HttpRequest
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

# PÁGINA PRINCIPAL
  
@login_required
def index(request):
    return render(request, "producto/index.html")


#! LISTAR CATEGORIA DE PRODUCTOS
# def productocategoria_list(request):
    #categorias = models.ProductoCategoria.objects.all()
    #contexto = {"categorias": categorias}
    #return render(request, "producto/productocategoria_list.html", contexto)
class ProductoCategoriaList(ListView):
    model = models.ProductoCategoria

#! CREAR CATEGORIA DE PRODUCTOS
#def productocategoria_create(request):
    #if request.method == "POST":  #! En caso de guardar datos
        #form = forms.ProductoCategoriaForm(request.POST)
        #if form.is_valid():
            #form.save()
            #return redirect("producto:home")  #! Cambia esto al nombre correcto de la URL de redirección
    #else:
        #form = forms.ProductoCategoriaForm()  #! Muestra el formulario
    #return render(request, "producto/productocategoria_form.html", {"form": form})   
class ProductoCategoriaCreate(CreateView):
    model = models.ProductoCategoria
    form_class = forms.ProductoCategoriaForm
    success_url = reverse_lazy("producto:productocategoria_list")



#! DETALLE DE CATEGORIA DE PRODUCTOS
#def productocategoria_detail(request, pk):
    #query = models.ProductoCategoria.objects.get(id=pk) #! Consulta a la base de datos
    #return render(request, "producto/productocategoria_detail.html", {"object": query})
class ProductoCategoriaDetail(DetailView):
    model = models.ProductoCategoria


#! ACTUALIZAR CATEGORIA DE PRODUCTOS
#def productocategoria_update(request, pk):
    #query = models.ProductoCategoria.objects.get(id=pk) #! Consulta a la base de datos
    #if request.method == "POST":  #! En caso de guardar datos
        #form = forms.ProductoCategoriaForm(request.POST, instance=query)
        #if form.is_valid():
            #form.save()
            #return redirect("producto:home") 
        #else:
            #form = forms.ProductoCategoriaForm(instance=query) 
        #return render(request, "producto/productocategoria_form.html", {"form": form})
class ProductoCategoriaUpdate(UpdateView):
    model = models.ProductoCategoria
    form_class = forms.ProductoCategoriaForm
    success_url = reverse_lazy("producto:productocategoria_list")



#! ELIMINAR CATEGORIA DE PRODUCTOS
#def productocategoria_delete(request: HttpRequest, pk: int) -> HttpResponse:
    #query = models.ProductoCategoria.objects.get(id=pk)
    #if request.method == "POST":
        #query.delete()
        #return redirect("producto:productocategoria_list.html")
    #return render(request, "producto/productocategoria_confirm_delete.html", {"object": query})
class ProductoCategoriaDelete(DeleteView):
    model = models.ProductoCategoria
    success_url = reverse_lazy("producto:productocategoria_list")
    

##################################################################################################################################################

#! LISTAR PRODUCTOS 
class ProductoList(ListView):
    model = models.Producto
    success_url = reverse_lazy("producto:producto_list")


#! CREAR PRODUCTOS
class ProductoCreate(CreateView):
    model = models.Producto
    form_class = forms.ProductoForm
    success_url = reverse_lazy("producto:producto_list")

#! DETALLE DE PRODUCTOS
class ProductoDetail(DetailView):
    model = models.Producto    
    success_url = reverse_lazy("producto:producto_detail")

#! ACTUALIZAR PRODUCTOS
class ProductoUpdate(UpdateView):
    model = models.Producto
    form_class = forms.ProductoForm
    success_url = reverse_lazy("producto:producto_list")

#! ELIMINAR PRODUCTOS
class ProductoDelete(DeleteView):
    model = models.Producto
    form_class = forms.ProductoForm
    success_url = reverse_lazy("producto:producto_list")

project/apps/producto/templates/producto/index.html
{% extends 'Home/index.html' %}

{% block INDEX_TITULO %}
   Productos
   {% endblock INDEX_TITULO %}
   
   {% block INDEX_CONTENIDO %}
   <h3 class="pb-lg-3">Categoria de Productos</h3>

   <div class="d-grid gap-3">
      <a href="{% url 'producto:productocategoria_create' %}">Crear Categoría de Productos></a>
      <a href="{% url 'producto:productocategoria_list' %}">Listar Productos</a>>
   </div>

      <h3 class="pb-lg-3">Productos</h3>
      <div class="d-grid gap-3">

         <a href="{% url 'producto:producto_create' %}">Crear Productos></a>
         <a href="{% url 'producto:producto_list' %}">Listar Productos</a>>
      </div>

      <a href="{% url 'Home:home' %}">Volver</a>
{% endblock INDEX_CONTENIDO %}

project/apps/producto/templates/producto/producto_confirm_delete.html
{% extends 'producto/index.html' %}

{% block INDEX_TITULO %}
    Eliminar Productos
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
   <p class="fs-5 fst-italic">¿Estas seguro que deseas eliminar el/los producto/s {{ object }}?</p>
   <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
   </form>
    <a href="{% url 'Home:home' %}">Volver</a>
{% endblock INDEX_CONTENIDO %}

project/apps/producto/templates/producto/producto_detail.html
{% extends 'producto/index.html' %}

{% block INDEX_TITULO %}
    Detalles de Productos
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
   <ul>
    <li>
        Categoria {{ object.categoria }}
    </li>
    <li>
        Nombre: {{ object.nombre }}
    </li>
    <li>
        Unidad de Medida: {{ object.unidad_de_medida }}
    </li>
    <li>
        Cantidad: {{ object.cantidad }}
    </li>
    <li>
        Precio: {{ object.precio }}
    </li>
    <li>
        Descripción: {{ object.descripcion }}
    </li>
    <li>
        Fecha de Actualización: {{ object.fecha_actualizacion }}
    </li>
   </ul>
    <a href="{% url 'Home:home' %}">Volver</a>
{% endblock INDEX_CONTENIDO %}

project/apps/producto/templates/producto/producto_form.html
{% extends 'producto/index.html' %}

{% block INDEX_TITULO %}
    Crear o Actualizar Productos
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    <form  method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>
    <a href="{% url 'Home:home' %}">Volver</a>
{% endblock INDEX_CONTENIDO %}

project/apps/producto/templates/producto/producto_list.html
{% extends 'producto/index.html' %}

{% block INDEX_TITULO %}
    Lista de Productos
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    {% if object_list %}
        <ul>
            {% for object in object_list %}
                <li>
                    {{ object.nombre }} - {{ object.precio }}
                    <a href="{% url 'producto:producto_detail' object.id %}" class="btn btn-primary">Ver detalles</a>
                    <a href="{% url 'producto:producto_update' object.id %}" class="btn btn-success">Actualizar</a>
                    <a href="{% url 'producto:producto_delete' object.id %}" class="btn btn-danger">Eliminar</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No hay elementos</p>
    {% endif %}
    <a href="{% url 'Home:home' %}">Volver</a>
{% endblock INDEX_CONTENIDO %}

project/apps/producto/templates/producto/productocategoria_confirm_delete.html
{% extends 'producto/index.html' %}

{% block INDEX_TITULO %}
    Eliminar Categoría de Productos
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
   <p class="fs-5 fst-italic">¿Estas seguro que deseas eliminar la categoría {{ object }}?</p>
   <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
   </form>
    <a href="{% url 'Home:home' %}">Volver</a>
{% endblock INDEX_CONTENIDO %}

project/apps/producto/templates/producto/productocategoria_detail.html
{% extends 'producto/index.html' %}

{% block INDEX_TITULO %}
    Detalles de Categoría de Productos
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
   <ul>
    <li>
        Nombre: {{ object.nombre }}
    </li>
    <li>
        Descripción: {{ object.descripcion }}
    </li>
   </ul>
    <a href="{% url 'Home:home' %}">Volver</a>
{% endblock INDEX_CONTENIDO %}

project/apps/producto/templates/producto/productocategoria_form.html
{% extends 'producto/index.html' %}

{% block INDEX_TITULO %}
    Crear o Actualizar la Categoría de Productos
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    <form  method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>
    <a href="{% url 'Home:home' %}">Volver</a>
{% endblock INDEX_CONTENIDO %}

project/apps/producto/templates/producto/productocategoria_list.html
{% extends 'producto/index.html' %}

{% block INDEX_TITULO %}
    Lista de Categorías de Productos
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    {% if object_list %}
        <ul>
            {% for object in object_list %}
                <li>
                    {{ object.nombre }} - {{ object.descripcion }}
                    <a href="{% url 'producto:productocategoria_detail' object.id %}" class="btn btn-primary">Ver detalles</a>
                    <a href="{% url 'producto:productocategoria_update' object.id %}" class="btn btn-success">Actualizar</a>
                    <a href="{% url 'producto:productocategoria_delete' object.id %}" class="btn btn-danger">Eliminar</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No hay elementos</p>
    {% endif %}
    <a href="{% url 'Home:home' %}">Volver</a>
{% endblock INDEX_CONTENIDO %}